/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import googleMaps from "@amicaldo/strapi-google-maps/strapi-admin";
import ckeditor from "@ckeditor/strapi-plugin-ckeditor/strapi-admin";
import calendar from "@offset-dev/strapi-calendar/strapi-admin";
import strapiCloud from "@strapi/plugin-cloud/strapi-admin";
import graphql from "@strapi/plugin-graphql/strapi-admin";
import i18N from "@strapi/plugin-i18n/strapi-admin";
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import scheduler from "@webbio/strapi-plugin-scheduler/strapi-admin";
import allInOneAccessibility from "../../node_modules/strapi-plugin-all-in-one-accessibility/strapi-admin";
import todo from "strapi-plugin-todo/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    "google-maps": googleMaps,
    ckeditor: ckeditor,
    calendar: calendar,
    "strapi-cloud": strapiCloud,
    graphql: graphql,
    i18n: i18N,
    seo: seo,
    "users-permissions": usersPermissions,
    scheduler: scheduler,
    "all-in-one-accessibility": allInOneAccessibility,
    todo: todo,
  },
});
